image: node:latest

stages:
  - installation
  - test
cache:
  paths:
    - node_modules/
installation:
  stage:  installation
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
test:
  stage:  test
  script: npm run coverage
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
